[package]
name = "x3"
version = "0.1.0"
authors = ["Simon M. Werner <simonwerner@gmail.com>"]
license = "GPL-v3"
readme = "README.md"
edition = "2018"

[build-dependencies]
clippy = { version = "*", optional = true }

[dependencies]
byteorder = { version = "1.3.1", default-features = false }
hound = "3.4.0"
quick-xml = "0.13.2"
clap = "2.32.0"
